export enum Currency {
    USD = 1,
    GBP = 2,
    EUR = 3,
    CHF = 4,
    RUB = 5,
    PLN = 6,
    BRL = 7,
    JPY = 8,
    NOK = 9,
    IDR = 10,
    MYR = 11,
    PHP = 12,
    SGD = 13,
    THB = 14,
    VND = 15,
    KRW = 16,
    TRY = 17,
    UAH = 18,
    MXN = 19,
    CAD = 20,
    AUD = 21,
    NZD = 22,
    CNY = 23,
    INR = 24,
    CLP = 25,
    PEN = 26,
    COP = 27,
    ZAR = 28,
    HKD = 29,
    TWD = 30,
    SAR = 31,
    AED = 32,
    SEK = 33,
};

export const CurrencyType = {
    USD: 'us-dollar',
    GBP: 'pound',
    EUR: 'euro',
    CHF: 'franc',
    RUB: 'ruble',
    PLN: 'zloty',
    BRL: 'real',
    JPY: 'yen',
    NOK: 'krone',
    IDR: 'rupiah',
    MYR: 'ringgit',
    PHP: 'philippine-peso',
    SGD: 'singaporean-dollar',
    THB: 'baht',
    VND: 'dong',
    KRW: 'won',
    TRY: 'lira',
    UAH: 'hryvnia',
    MXN: 'mexican-peso',
    CAD: 'canadian-dollar',
    AUD: 'australian-dollar',
    NZD: 'new-zealand-dollar',
    CNY: 'renminbi',
    INR: 'rupee',
    CLP: 'chilean-peso',
    PEN: 'sol',
    COP: 'colombian-peso',
    ZAR: 'rand',
    HKD: 'hong-kong-dollar',
    TWD: 'taiwan-dollar',
    SAR: 'riyal',
    AED: 'dirham',
    SEK: 'krona',
};

export const CurrencySign = {
    USD: '$',
    GBP: '£',
    EUR: '€',
    CHF: 'SFr.',
    RUB: '₽',
    PLN: 'zł',
    BRL: 'R$',
    JPY: '¥',
    NOK: 'kr',
    IDR: 'Rp',
    MYR: 'RM',
    PHP: '₱',
    SGD: '$',
    THB: '฿',
    VND: '₫',
    KRW: '₩',
    TRY: '₺',
    UAH: '₴',
    MXN: '$',
    CAD: '$',
    AUD: '$',
    NZD: '$',
    CNY: '¥',
    INR: '₹',
    CLP: '$',
    PEN: 'S/',
    COP: '$',
    ZAR: 'R',
    HKD: '$',
    TWD: 'NT$',
    SAR: 'ر.س',
    AED: 'د.إ',
    SEK: 'kr',
};

export enum Application {
    CSGO                         = 730,
    DOTA2                        = 570,
    H1Z1_JUSTSURVIVE             = 295110,
    H1Z1_KINGOFTHEKILL           = 433850,
    KILLING_FLOOR2               = 232090,
    PAYDAY2                      = 218620,
    PLAYERUNKNOWNS_BATTLEGROUNDS = 578080,
    RUST                         = 252490,
    TF2                          = 440,
    UNTURNED                     = 304930,
};
